[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"
  site_name = "flickcast"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "16"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://js.paystack.co https://www.gstatic.com https://pagead2.googlesyndication.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      connect-src 'self' https://api.stripe.com https://api.paystack.co https://firestore.googleapis.com;
      frame-src 'self' https://js.stripe.com https://standard.paystack.co;
      media-src 'self' blob:;
    """

[dev]
  command = "npm run dev"
  port = 8888
  publish = "dist"

# Environment variable placeholders (replace these in Netlify dashboard)
[template]
  name = "FlickCast"
  description = "A premium screen recording application with Stripe and Paystack integration"

[template.environment]
  SITE_NAME = "FlickCast"
  STRIPE_SECRET_KEY = "Your Stripe Secret Key"
  STRIPE_PUBLIC_KEY = "Your Stripe Public Key"
  PAYSTACK_SECRET_KEY = "Your Paystack Secret Key"
  PAYSTACK_PUBLIC_KEY = "Your Paystack Public Key"
  FIREBASE_API_KEY = "AIzaSyB70NsWSoqAK--V57XsoWov8V6whlVDu70"
  FIREBASE_AUTH_DOMAIN = "flickcast-6fe9c.firebaseapp.com"
  FIREBASE_PROJECT_ID = "flickcast-6fe9c"
  FIREBASE_STORAGE_BUCKET = "flickcast-6fe9c.firebasestorage.app"
  FIREBASE_MESSAGING_SENDER_ID = "790285114908"
  FIREBASE_APP_ID = "1:790285114908:web:d6ee2d00272f214d0209d9" 